logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
    com:
      exzray: debug

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create
  datasource:
    hikari:
      pool-name: database-pool
      maximum-pool-size: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/development
    driverClassName: com.mysql.cj.jdbc.Driver

